Remove redundant `struct` keys
Because this is C++ code, GCC 12 says things like:

    Socket.hpp:166:24: error:
    redundant class-key ‘struct’ in reference to ‘struct sockaddr_un’
    [-Werror=redundant-tags]